Repository Health-Food-Me/Health-Food-Me-Android, pull requests merged in 2022-09, with the labels that each got.

#257 [ui] 둘러보기 화면 디자인
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#258 [fix] #215 - 상세 뷰에서 상단 스크랩 버튼 누를 경우 메뉴 탭으로 이동되는 버그 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
Labels: 영진🐶, DONE, BUG

#264 [feat] #263 - 블로그 리뷰 웹뷰로 보여주기 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/common/WebViewActivity.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/res/layout/activity_web_view.xml
Labels: 영진🐶, DONE

#268 [fix] 마커 관련 버그 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/util/ext/ContextExt.kt
Labels: 다빈😺, DONE

#271 [ui] #270 내가 쓴 리뷰 리스트 패딩 변경
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantGeneralReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/org/helfoome/util/ItemDecorationUtil.kt
  app/src/main/res/layout/activity_my_review.xml
Labels: 준경🔥, In Progress

#266 [mod] 스크랩 영역 변경
  app/src/main/res/layout/dialog_gallery_image_selection.xml
  app/src/main/res/layout/dialog_map_selection.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/layout/item_recent_word.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: 준경🔥, In Progress

#269 [ui] 비회원 로그인 간편로그인 제공 다이얼로그 디자인
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/withdrawal/WithdrawalActivity.kt
  app/src/main/java/org/helfoome/util/ext/ContextExt.kt
  app/src/main/res/layout/dialog_guest_login_support.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/dialog_my_review_delete.xml
  app/src/main/res/layout/dialog_my_review_edit.xml
  app/src/main/res/layout/dialog_withdraw.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#277 [refactor] #275 loginActivity 애니메이션 함수화
  app/src/main/java/org/helfoome/presentation/login/LoginActivity.kt
Labels: 준경🔥, In Progress

#280 [fix] 리뷰 편집 시 기존 내용을 불러오지 못하는 버그 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseMyReviewList.kt
  app/src/main/java/org/helfoome/domain/entity/MyReviewInfo.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewViewModel.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/review/RestaurantReviewWritingViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/util/HashtagUtil.kt
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/item_general_my_review.xml
  app/src/main/res/values/strings.xml
Labels: 영진🐶, DONE

#282 [fix] #281 리뷰 업로드 시 별점 0.5점을 부여할 경우, 별점이 올바르게 표시되지 않는 버그를 수정
  app/src/main/java/org/helfoome/presentation/custom/StarScore.kt
Labels: 영진🐶, DONE, BUG

#279 [feat] 둘러보기 구현
  app/src/main/java/org/helfoome/data/local/HFMSharedPreference.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/drawer/SettingActivity.kt
  app/src/main/java/org/helfoome/presentation/login/GuestLoginFragmentDialog.kt
  app/src/main/java/org/helfoome/presentation/login/LoginActivity.kt
  app/src/main/java/org/helfoome/util/BindingAdapter.kt
  app/src/main/res/layout/activity_main_drawer_header.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/dialog_guest_login_support.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 준경🔥, In Progress

#290 [fix] #283 내 리뷰 good 해시 태그 포맷 버그 수정
  app/src/main/java/org/helfoome/presentation/custom/HashtagView.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
Labels: 영진🐶, DONE, BUG

#292 [fix] #291 리뷰 작성 시 레스토랑 이름을 불러오지 못하는 버그를 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
Labels: 영진🐶, DONE, BUG

#296 [fix] #295 햄버거바에서 닉네임이 뜨지 않는 버그 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseProfile.kt
Labels: 영진🐶, DONE, BUG

#301 [feat] 식당 리스트 조회 Response Body 수정된 것 반영
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
Labels: 다빈😺, DONE

#302 [ui] 스크랩한 스낵바 설정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/login/GuestLoginFragmentDialog.kt
  app/src/main/res/layout/dialog_guest_login_support.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: 준경🔥, In Progress

#304 [mod] #303 api 변경으로 인한 식당 상세정보 response 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseRestaurantDetail.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseRestaurantSummary.kt
  app/src/main/java/org/helfoome/domain/entity/RestaurantInfo.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/res/layout/dialog_search_restaurant_detail.xml
Labels: 영진🐶, DONE

#294 [refactor] 상세뷰 프래그먼트화
  app/src/main/java/org/helfoome/data/model/response/ResponseScrapData.kt
  app/src/main/java/org/helfoome/domain/entity/ScrapInfo.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/detail/RestaurantDetailFragment.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/presentation/search/adapter/ResultAdapter.kt
  app/src/main/java/org/helfoome/util/EventFlow.kt
  app/src/main/java/org/helfoome/util/ext/ActivityExt.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_map_select.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/layout/fragment_restaurant_detail.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 다빈😺, In Progress

#310 [feat] 외식대처법 카테고리 2개 이상 대응되도록 구현
  app/src/main/java/org/helfoome/data/model/response/ResponseEatingOutTip.kt
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/RestaurantService.kt
  app/src/main/java/org/helfoome/domain/repository/RestaurantRepository.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/custom/EatingOutTipView.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantEatingOutTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/viewmodel/RestaurantMenuViewModel.kt
  app/src/main/java/org/helfoome/util/BindingAdapter.kt
  app/src/main/res/color/selector_eating_out_category_text_color.xml
  app/src/main/res/drawable/selector_eating_out_category_background.xml
  app/src/main/res/layout/fragment_eating_out.xml
  app/src/main/res/values/themes.xml
Labels: 영진🐶, DONE

#312 [feat] 식당 상세뷰 메뉴판 이미지 보여주기 구현
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantMenuTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantMenuBoardAdapter.kt
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/item_menu_board.xml
  app/src/main/res/values/strings.xml
Labels: 영진🐶, DONE

#315 [fix] #311 상세뷰에서 스크랩이 동작하지 않는 버그 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseScrap.kt
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/repository/ScrapRepositoryImpl.kt
  app/src/main/java/org/helfoome/domain/repository/RestaurantRepository.kt
  app/src/main/java/org/helfoome/domain/repository/ScrapRepository.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
Labels: 영진🐶, DONE, BUG

#318 [mod] 블로그 리뷰 불러오기 response 수정
  app/src/main/java/org/helfoome/data/datasource/RemoteRestaurantDataSource.kt
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/RestaurantService.kt
  app/src/main/java/org/helfoome/domain/repository/RestaurantRepository.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
Labels: 영진🐶, DONE

#322 [fix] #321 길찾기 다이얼로그에서 버튼이 클릭되지 않는 버그를 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/detail/RestaurantDetailFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/MapSelectionBottomDialogFragment.kt
Labels: 영진🐶, DONE, BUG

#323 [mod] #289 로그아웃, 편집취소, 작성취소, 다이얼로그 Alert 프래그먼트화
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/alert/AlertFragmentDialog.kt
  app/src/main/java/org/helfoome/presentation/alert/AlertViewModel.kt
  app/src/main/java/org/helfoome/presentation/detail/RestaurantDetailFragment.kt
  app/src/main/java/org/helfoome/presentation/login/GuestLoginFragmentDialog.kt
  app/src/main/java/org/helfoome/presentation/review/RestaurantReviewWritingViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/org/helfoome/presentation/type/AlertType.kt
  app/src/main/res/layout/dialog_alert.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#327 [mod] #325 외식대처법 카테고리 중앙 정렬로 수정
  app/src/main/res/layout/fragment_eating_out.xml
Labels: 영진🐶, DONE

#330 [mod] 리뷰 관련 reponse 수정 및 헬푸미 리뷰 조회 버그 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseHFMReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseMyReviewEdit.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseMyReviewList.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseReview.kt
  app/src/main/java/org/helfoome/data/service/ReviewService.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/java/org/helfoome/presentation/review/RestaurantReviewWritingViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
Labels: 영진🐶, DONE, BUG

#334 [chore] #333 - 상태바 투명 옵션 메인뷰에서 제거
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: 다빈😺, DONE

#335 [mod] 유저 리뷰 모아보기 뷰 레이아웃 수정
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/res/layout/item_general_my_review.xml
Labels: 영진🐶, DONE

#336 [mod] dialog alert 창 크기 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/alert/AlertFragmentDialog.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/ReviewDeleteFragmentDialog.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/org/helfoome/presentation/withdrawal/WithdrawFragmentDialog.kt
  app/src/main/java/org/helfoome/presentation/withdrawal/WithdrawalActivity.kt
  app/src/main/java/org/helfoome/util/DialogUtil.kt
  app/src/main/java/org/helfoome/util/ext/ContextExt.kt
  app/src/main/res/layout/dialog_alert.xml
  app/src/main/res/layout/dialog_my_review_delete.xml
  app/src/main/res/layout/dialog_withdraw.xml
Labels: 준경🔥, In Progress

#338 [fix] 리뷰 삭제 다이얼로그에서 “네” 버튼을 눌러도 리뷰가 삭제되지 않는 버그 수정
  app/src/main/java/org/helfoome/presentation/drawer/ReviewDeleteFragmentDialog.kt
Labels: 영진🐶, DONE, BUG

#340 [del] #339 getScreenSize 함수 삭제
  app/src/main/java/org/helfoome/util/ext/ContextExt.kt
Labels: 준경🔥, In Progress

#342 [fix] 영업정보 없음 TextView와 전화번호 TextView가 겹쳐보이는 버그 수정
  app/src/main/res/layout/fragment_restaurant_detail.xml
Labels: 영진🐶, DONE, BUG

#343 [fix] 마커 겹쳤을 때 사라지게 하는 옵션 제거
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
Labels: 다빈😺, DONE

#347 [feat] 식당정보 요약 뷰 스크롤 위로 고정되게 변경
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/detail/RestaurantDetailFragment.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
Labels: 다빈😺, DONE

#351 [fix] 스크랩 뷰 버그 해결
  app/src/main/java/org/helfoome/presentation/scrap/MyScrapActivity.kt
Labels: 다빈😺, DONE

#366 [mod] '외식 대처법'-> '외식대처법' ui 라이팅 변경
  app/src/main/res/values/strings.xml
Labels: 영진🐶, DONE

#370 [feat] 현재 위치로 이동 버튼 기능 추가
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
Labels: 다빈😺, DONE

#372 [ui] 다이어트 식당 핀 색깔 변경
  app/src/main/res/drawable/ic_marker_green_big.xml
  app/src/main/res/drawable/ic_marker_red_big.xml
Labels: 다빈😺, DONE

#374 [ui] 서치 뷰 UI QA 반영
  app/src/main/res/drawable/rectangle_border_bottom_white_grey.xml
  app/src/main/res/layout/item_auto_complete_word.xml
  gradle/libs.versions.toml
Labels: 다빈😺, DONE

#376 [feat] 스크랩 버튼 취소시, 상단 카테고리 메뉴 리스트 선택 동시 취소
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
Labels: 다빈😺, DONE

#378 [feat] 싱글 클릭리스너 추가
  app/src/main/java/org/helfoome/util/ext/ViewExt.kt
Labels: 다빈😺, DONE

#344 [feat] #309 스크랩 한 식당 토스트메시지 API 연결
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/res/layout/view_snackbar.xml
Labels: 준경🔥, In Progress

#348 [ui] #345 비회원 로그인 다이얼로그 창 디자인 수정
  app/src/main/res/drawable/btn_login_cancel.xml
  app/src/main/res/drawable/ic_kakao_login_small.xml
  app/src/main/res/drawable/ic_naver_login_small.xml
  app/src/main/res/layout/dialog_guest_login_support.xml
Labels: 준경🔥, In Progress

#354 [mod] #349 설정 탭 수정
  app/src/main/java/org/helfoome/presentation/drawer/SettingActivity.kt
  app/src/main/java/org/helfoome/presentation/withdrawal/WithdrawFragmentDialog.kt
  app/src/main/java/org/helfoome/presentation/withdrawal/WithdrawalActivity.kt
  app/src/main/res/layout/activity_setting.xml
Labels: 준경🔥, In Progress

#356 [ui] #355 햄버거 바 마진 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main_drawer_header.xml
Labels: 준경🔥, In Progress

#358 [mod] #357 검색바 UX 라이팅 변경
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#380 [mod] 홈화면 카테고리 변경
  app/src/main/java/org/helfoome/presentation/type/FoodType.kt
  app/src/main/res/drawable/ic_steak.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#383 [fix] #382 내가 쓴 리뷰 버그 수정
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/res/layout/activity_my_review.xml
Labels: 준경🔥, In Progress

#384 [ui] #379 태그 그림자 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: 준경🔥, In Progress

#386 [feat] 화면 회전 막기
  app/src/main/AndroidManifest.xml
  gradle/common.gradle
Labels: 다빈😺, DONE

#389 [fix] 상세뷰 영업시간 토글을 펼친 상태에서 다른 식당 핀을 눌렀을 경우, 여전히 토글이 펼쳐저 있...
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
Labels: 다빈😺, DONE

#390 [feat] 상세뷰 영업시간 토글 펼쳤을 때 현재 요일 볼드 처리
  app/src/main/java/org/helfoome/presentation/custom/OpeningTimeView.kt
Labels: 영진🐶, DONE

#391 [fix] #368 - 상세뷰 외식 대처법 글자 짤림 버그 수정
  app/src/main/res/layout/item_eating_out_tip.xml
Labels: 영진🐶, DONE, BUG

#393 [mod] 리뷰 작성 완료 조건 변경
  app/src/main/java/org/helfoome/presentation/review/RestaurantReviewWritingViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/res/values/strings.xml
Labels: 영진🐶, DONE

#395 [fix] 길찾기 앱 연동 시 crash가 발생하는 버그 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/MapSelectionBottomDialogFragment.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
Labels: 영진🐶, DONE, BUG

#398 [feat] 레이아웃 취급방침 메뉴 임시로 추가
  app/src/main/java/org/helfoome/presentation/drawer/SettingActivity.kt
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/strings.xml
Labels: 영진🐶, DONE
