Repository Health-Food-Me/Health-Food-Me-Android, pull requests merged in 2022-08, with the labels that each got.

#227 [feat] 스낵바 유틸 만들기
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/custom/SnackBarView.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/util/SnackBarTopDown.kt
Labels: 준경🔥, In Progress

#229 [feat] 스크랩 필터
  app/src/main/java/org/helfoome/domain/usecase/ScrapListUseCase.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
Labels: 다빈😺, DONE

#235 [mod] #234 - Splash 액티비티 패키징
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/splash/SplashActivity.kt
  app/src/main/java/org/helfoome/presentation/splash/SplashSecondActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_splash_second.xml
Labels: 준경🔥, In Progress

#230 [fix] 지도앱이 설치되어있는 경우에도 플레이스토어 링크로 이동하는 버그 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/domain/entity/LocationPointInfo.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/MapSelectionBottomDialogFragment.kt
Labels: 영진🐶, In Progress

#240 [mod] #231 - 리뷰 작성 완료 텍스트 수정
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#236 [feat] 스크랩 뷰 로직
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MyScrapActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/ScrapViewModel.kt
  app/src/main/res/layout/activity_map_select.xml
  app/src/main/res/layout/activity_my_scrap.xml
Labels: 다빈😺, DONE

#239 [feat] 리뷰 쓰기 완료후 해당 식당 리뷰 작성 확인 반영되게 하기
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/res/drawable-xxhdpi/selector_text_modify.xml
Labels: 준경🔥, In Progress

#243 [refactor] 힐트 @Provides 어노테이션 @Binds로 수정
  app/src/main/java/org/helfoome/data/repository/MapRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/helfoome/di/AppModule.kt
  app/src/main/java/org/helfoome/di/RepositoryModule.kt
Labels: 다빈😺, DONE

#246 [chore] 소셜 로그인 분기처리하기
  app/src/main/java/org/helfoome/di/NetworkModule.kt
Labels: 다빈😺, In Progress

#248 [feat] 지도 뷰 겹치는 마커 숨기기 및 캡션 추가
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
Labels: 다빈😺, DONE

#251 [mod] #250 - ToastMessage 유틸 삭제
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/org/helfoome/util/ToastMessage.kt
Labels: 준경🔥, In Progress

#252 [mod] #249 - 리뷰 불러오기 api 한번만 하게 변경
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
Labels: 준경🔥, In Progress

#254 [mod] #245 클릭 리스너 람다에서 고차함수로 통일
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/res/layout/item_general_my_review.xml
Labels: 준경🔥, In Progress
