Repository Health-Food-Me/Health-Food-Me-Android, pull requests merged in 2022-10, with the labels that each got.

#405 [mod] 상세뷰 레이아웃 배치 조정
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantMenuTabFragment.kt
  app/src/main/res/layout/fragment_eating_out.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_restaurant_detail.xml
  app/src/main/res/layout/item_general_review.xml
  app/src/main/res/values/dimens.xml
Labels: 영진🐶, DONE

#406 [mod] - 상세뷰 상단바 하단에 그림자 제거
  app/src/main/res/layout/fragment_restaurant_detail.xml
Labels: 영진🐶, DONE

#411 [ui] #408 다이얼로그 네,아니오 사이즈 수정
  app/src/main/res/layout/dialog_alert.xml
  app/src/main/res/layout/dialog_my_review_delete.xml
  app/src/main/res/layout/dialog_withdraw.xml
Labels: 준경🔥, In Progress

#413 [ui] #412 다이얼로그 전체 크기 수정
  app/src/main/java/org/helfoome/presentation/alert/AlertFragmentDialog.kt
  app/src/main/res/layout/dialog_alert.xml
Labels: 준경🔥, In Progress

#415 [feat] 위치 권한 구현
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/alert/ConfirmFragmentDialog.kt
  app/src/main/java/org/helfoome/presentation/alert/ConfirmViewModel.kt
  app/src/main/java/org/helfoome/presentation/type/ConfirmType.kt
  app/src/main/res/layout/dialog_confirm.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#419 [feat] 바뀐 명세서 바디 값(스크랩, 검색 결과) 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseScrapData.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseSearchCard.kt
  app/src/main/java/org/helfoome/domain/entity/ScrapInfo.kt
  app/src/main/java/org/helfoome/domain/entity/SearchResultInfo.kt
Labels: 다빈😺, DONE

#420 [fix] API 수정에 따른 필터 로직 제거
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/scrap/MyScrapActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/ScrapViewModel.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/util/ext/MarkerFilter.kt
Labels: 다빈😺, DONE

#421 [feat] 메뉴판 및 리뷰 이미지 뷰어 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/common/ImageViewerActivity.kt
  app/src/main/java/org/helfoome/presentation/common/PhotoSlideAdapter.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantMenuTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantGeneralReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantImageAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantMenuBoardAdapter.kt
  app/src/main/res/drawable/ic_close_white.xml
  app/src/main/res/layout/activity_image_viewer.xml
  app/src/main/res/layout/item_photo_slide.xml
  app/src/main/res/values/strings.xml
Labels: 영진🐶, DONE

#423 [mod] 설정탭 레이아웃 둘러보기 분기처리
  app/src/main/res/layout/activity_setting.xml
Labels: 영진🐶, DONE

#425 [mod] 웹뷰로 화면전환 시 화면전환 애니메이션 제거
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
Labels: 영진🐶, DONE

#430 [mod] 상세뷰 외식대처법 엠티뷰 분기처리 로직 수정
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantEatingOutTabFragment.kt
  app/src/main/res/layout/fragment_eating_out.xml
Labels: 영진🐶, DONE

#431 [mod] #429 닉네임 부적합 조건 변경
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyViewModel.kt
Labels: 준경🔥, In Progress

#433 [fix] 스크랩 관련 버그 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseScrapData.kt
  app/src/main/java/org/helfoome/domain/entity/ScrapInfo.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MyScrapActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/ScrapViewModel.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
Labels: 다빈😺, DONE

#435 [mod] #434 스낵바 패딩 변경
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
Labels: 준경🔥, DONE

#439 [feat] 블로그 리뷰 웹뷰 ui 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/common/WebViewActivity.kt
  app/src/main/res/drawable/background_dialog_top_corner.xml
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/layout/activity_web_view.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 영진🐶, DONE

#441 [mod] 설정탭 약관 및 정책 및 상단 메뉴 사이 간격 수정
  app/src/main/res/layout/activity_setting.xml
Labels: 영진🐶, DONE

#444 [ui] #442 닉네임, 로그인이 필요해요 bold처리 및 상단 마진 수정
  app/src/main/res/layout/activity_main_drawer_header.xml
Labels: 준경🔥, In Progress

#445 [ui] #443 alert 창 타이틀 폰트 Medium 처리 및 리뷰 취소 마진 수정
  app/src/main/res/layout/dialog_alert.xml
  app/src/main/res/layout/dialog_confirm.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/dialog_my_review_delete.xml
  app/src/main/res/layout/dialog_my_review_edit.xml
  app/src/main/res/layout/dialog_withdraw.xml
Labels: 준경🔥, In Progress

#448 [feat] 이미지 뷰어에서 이미지 저장 기능 구현
  app/src/main/java/org/helfoome/presentation/common/ImageViewerActivity.kt
Labels: 영진🐶, DONE

#449 [ui] #447 alert 창 lineSpacingExtra 추가
  app/src/main/res/layout/dialog_alert.xml
  app/src/main/res/layout/dialog_confirm.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/dialog_my_review_delete.xml
  app/src/main/res/layout/dialog_my_review_edit.xml
  app/src/main/res/layout/dialog_withdraw.xml
Labels: 준경🔥, In Progress

#454 [fix] 플레이스토어에서 애플리케이션 다운로드 되지않는 버그 수정
  app/src/main/AndroidManifest.xml
  gradle/libs.versions.toml
Labels: 다빈😺, DONE

#452 [fix] 검색 뷰 버그 수정
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/res/layout/activity_search.xml
Labels: 다빈😺, DONE, BUG

#455 [feat] 자동로그인 로직 다시 추가
  app/src/main/java/org/helfoome/HFMApplication.kt
  app/src/main/java/org/helfoome/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/helfoome/data/local/HFMSharedPreference.kt
  app/src/main/java/org/helfoome/data/service/KakaoAuthService.kt
  app/src/main/java/org/helfoome/data/service/NaverAuthService.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/alert/AlertFragmentDialog.kt
  app/src/main/java/org/helfoome/presentation/alert/AlertViewModel.kt
  app/src/main/java/org/helfoome/presentation/alert/ConfirmFragmentDialog.kt
  app/src/main/java/org/helfoome/presentation/alert/ConfirmViewModel.kt
  app/src/main/java/org/helfoome/presentation/detail/RestaurantDetailFragment.kt
  app/src/main/java/org/helfoome/presentation/login/GuestLoginFragmentDialog.kt
  app/src/main/java/org/helfoome/presentation/login/LoginActivity.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/org/helfoome/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/activity_main_drawer_header.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/dialog_confirm.xml
  app/src/main/res/values/strings.xml
Labels: 다빈😺, DONE

#456 [fix] 상세뷰 스크롤 이슈 해결
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantEatingOutTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantMenuTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/res/layout/fragment_eating_out.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_restaurant_detail.xml
  app/src/main/res/layout/fragment_review.xml
Labels: 다빈😺, DONE, BUG

#450 [feat] #402 댓글에서 상세페이지로 이동
  app/src/main/java/org/helfoome/data/model/response/ResponseMyReviewList.kt
  app/src/main/java/org/helfoome/domain/entity/MyReviewInfo.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/detail/RestaurantDetailFragment.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/res/layout/activity_my_review.xml
Labels: 준경🔥, In Progress

#459 [fix] #458 둘러보기 재로그인 버그 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/login/GuestLoginFragmentDialog.kt
  app/src/main/res/layout/activity_main_drawer_header.xml
Labels: 준경🔥, In Progress

#463 [mod] 상세뷰 뷰페이저 슬라이드 막기 해제
  app/src/main/java/org/helfoome/presentation/detail/RestaurantDetailFragment.kt
Labels: 영진🐶, DONE

#464 [mod] 최근 작성한 리뷰가 하단으로 추가되는 것처럼 보이는 버그 수정
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
Labels: 영진🐶, DONE

#467 [fix] - 메뉴탭, 외식대처법 탭에서도 리뷰쓰기 버튼이 보이는 버그 수정
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
Labels: 영진🐶, DONE

#468 [feat] 중심좌표 이동 시 핀 재호출 로직 추가
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
Labels: 다빈😺, DONE

#470 [mod] - 상세뷰 메뉴탭 메뉴 정렬 방식 수정
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
Labels: 영진🐶, DONE

#472 [fix] 내가 쓴 리뷰 > 리뷰 아이템 > 식당명 클릭 시 이동하는 상세뷰에서 요약정보 뷰일 때 보이는 상단 다이얼로그 라인이 보이는 버그 수정
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
Labels: 영진🐶, DONE

#474 [fix] - 메일 앱 연동 시 올바르지 않은 이메일 및 메일 내용을 변경
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/SettingActivity.kt
  app/src/main/res/values/strings.xml
Labels: 영진🐶, DONE, BUG

#475 [fix] 검색 뷰 4차 QA
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/res/drawable/ic_menu_search.xml
  app/src/main/res/layout/layout_look_map.xml
Labels: 다빈😺, DONE, BUG

#479 [fix] - #478 스크랩한 식당에서 식당 목록이 없을 때 Empty뷰가 보이지 않는 버그 수정
  app/src/main/java/org/helfoome/presentation/scrap/ScrapViewModel.kt
Labels: 영진🐶, DONE, BUG

#480 [fix] 검색 뷰 - 최근 검색어, 자동완성, 결과 뷰 관련 플로우 & 지도 버그 수정
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
Labels: 다빈😺, DONE, BUG

#482 [feat] 중심 좌표, 축적 관련 코드 정리
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MyScrapActivity.kt
Labels: 다빈😺, DONE

#485 [feat] 나의 리뷰 뷰에서 현재 로케이션 좌표 활용할 수 있게 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
Labels: 다빈😺, DONE

#492 [mod] #489 탈퇴완료시 스플래쉬 화면으로 이동
  app/src/main/java/org/helfoome/data/repository/WithdrawalRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/AuthService.kt
  app/src/main/java/org/helfoome/presentation/withdrawal/WithdrawalActivity.kt
Labels: 준경🔥, In Progress

#493 [fix] - #488 Empty 뷰 안보이는 버그 수정
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/res/layout/fragment_review.xml
Labels: 영진🐶, DONE, BUG

#494 [chore] leakCanary implementation 디버그로 변경
  app/build.gradle.kts
Labels: 다빈😺, DONE

#495 [fix] 카카오 로그인 관련 그래들 + 프로가드 수정
  app/build.gradle.kts
  app/proguard-rules.pro
Labels: 다빈😺, DONE

#497 [feat] 카메라 이동이 멈출 때 핀이 찍히도록 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  gradle/libs.versions.toml
Labels: 다빈😺, DONE

#499 [mod] #498 둘러보기 로그인이 필요해요 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
Labels: 준경🔥, In Progress

#501 [fix] Menu 데이터 클래스에서 kcal 프로퍼티를 Int -> Float로 변경
  app/src/main/java/org/helfoome/data/model/response/ResponseRestaurantDetail.kt
Labels: 영진🐶, DONE, BUG
