Repository Health-Food-Me/Health-Food-Me-Android, pull requests merged in 2022-07, with the labels that each got.

#3 [chore] 깃허브 액션 셋팅
  .editorconfig
  .github/workflows/pr_builder.yml
Labels: 다빈😺, DONE

#4 [feat] 프로젝트 기초세팅
  .idea/.gitignore
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/org/helfoome/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/HFMApplication.kt
  app/src/main/java/org/helfoome/data/EmptyFile.kt
  app/src/main/java/org/helfoome/domain/EmptyFile.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/util/HFMDebugTree.kt
  app/src/main/java/org/helfoome/util/binding/BindingActivity.kt
  app/src/main/java/org/helfoome/util/binding/BindingFragment.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/org/helfoome/ExampleUnitTest.kt
  build.gradle.kts
  gradle.properties
  gradle/common.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: 다빈😺, DONE

#13 [chore] 깃허브 액션 슬랙 연동
  .github/workflows/develop_merge_builder.yml
  .github/workflows/pr_builder.yml
  app/build.gradle.kts
  app/src/main/java/org/helfoome/data/EmptyFile.kt
  app/src/main/java/org/helfoome/domain/EmptyFile.kt
Labels: 다빈😺, DONE

#16 [feat] 최근 검색어 저장을 위한 Room 셋팅
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/data/local/dao/SearchDao.kt
  app/src/main/java/org/helfoome/data/local/database/HFMDatabase.kt
  app/src/main/java/org/helfoome/data/local/entity/SearchData.kt
  app/src/main/java/org/helfoome/di/DatabaseModule.kt
Labels: 다빈😺, DONE

#15 [feat] 홈화면 네이버 지도 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/HFMApplication.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/res/drawable/ic_bookmark.xml
  app/src/main/res/drawable/ic_currentposition.xml
  app/src/main/res/drawable/ic_hamburger.xml
  app/src/main/res/drawable/ic_marker_green.xml
  app/src/main/res/drawable/ic_marker_red.xml
  app/src/main/res/drawable/ic_sandwitch.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/rectangle_white_radius_14.xml
  app/src/main/res/drawable/rp_green_hambuger.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
Labels: 준경🔥, In Progress

#25 [add] #24 - GitHub Action 수정(로컬 프로퍼티 반영)
  .github/workflows/pr_builder.yml
Labels: 다빈😺, In Progress

#26 [mod] #7 홈화면 아이템들 위치 수정
  .idea/ktlint.xml
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/util/ToastMessage.kt
  app/src/main/res/drawable/ic_hambuger.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#20 [feat] 카카오, 네이버 로그인 ui 디자인 및 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/HFMApplication.kt
  app/src/main/java/org/helfoome/di/LoginModule.kt
  app/src/main/java/org/helfoome/presentation/KakaoAuthService.kt
  app/src/main/java/org/helfoome/presentation/LoginActivity.kt
  app/src/main/java/org/helfoome/presentation/NaverAuthService.kt
  app/src/main/res/drawable-xxxhdpi/rectangle_login_kakao.png
  app/src/main/res/drawable-xxxhdpi/rectangle_login_naver.png
  app/src/main/res/drawable/ic_btn_kakao_login.xml
  app/src/main/res/drawable/ic_btn_naver_login.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 준경🔥, In Progress

#30 [feat] 로그인 화면 로고 색깔 변경
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, DONE

#28 [feat] 홈화면 햄버거 바 디자인 및 구현
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_drawer_header.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 준경🔥, In Progress

#32 [feat] 3.0 기능명세서에서 변경사항을 반영하여 식당 상세페이지 뷰 구현
  app/src/main/java/org/helfoome/domain/entity/RestaurantInfo.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/custom/OpeningTimeView.kt
  app/src/main/java/org/helfoome/util/NestedCoordinatorLayout.kt
  app/src/main/res/drawable/ic_dropdown_down.xml
  app/src/main/res/drawable/ic_dropdown_up.xml
  app/src/main/res/drawable/selector_btn_dropdown.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/view_opening_time.xml
  app/src/main/res/values/themes.xml
Labels: 영진🐶

#34 [ui] 홈 화면 검색 ui
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/res/drawable/ic_before.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_delete_circle.xml
  app/src/main/res/drawable/rectangle_border_bottom_grey.xml
  app/src/main/res/drawable/rectangle_border_gray_radius_15.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_auto_complete_word.xml
  app/src/main/res/layout/item_recent_word.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/layout/layout_recent_word.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 다빈😺, DONE

#41 [chore] 깃허브 액션 apk 파일 추출 끄기
  .github/workflows/develop_merge_builder.yml
Labels: 다빈😺, DONE

#44 [mod] #43 - 로그인 화면 디자인 수정
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, DONE

#49 [feat] chip 버튼 클릭 구현
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/type/FoodType.kt
  app/src/main/java/org/helfoome/util/ChipFactory.kt
  app/src/main/java/org/helfoome/util/ext/ContextExt.kt
  app/src/main/res/color/selector_chip_bg_diet.xml
  app/src/main/res/color/selector_chip_bg_normal.xml
  app/src/main/res/color/selector_chip_icon_diet.xml
  app/src/main/res/color/selector_chip_icon_normal.xml
  app/src/main/res/color/selector_chip_text.xml
  app/src/main/res/drawable-xxhdpi/rectangle_wihte_radius_14.xml
  app/src/main/res/drawable/ic_bossam.xml
  app/src/main/res/drawable/ic_btn_currentposition.xml
  app/src/main/res/drawable/ic_dupbap.xml
  app/src/main/res/drawable/ic_kimbap.xml
  app/src/main/res/drawable/ic_meat.xml
  app/src/main/res/drawable/ic_poke.xml
  app/src/main/res/drawable/ic_salad.xml
  app/src/main/res/drawable/ic_sandwich.xml
  app/src/main/res/drawable/ic_shabushabu.xml
  app/src/main/res/drawable/rectangle_white_radius_14.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/view_chip_food.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 준경🔥, In Progress

#45 [feat] 로그아웃 구현 및 다이얼로그 구현
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/res/drawable-xhdpi/rectangle_green_radius_5.xml
  app/src/main/res/drawable-xhdpi/rectangle_red_radius_8.xml
  app/src/main/res/drawable-xhdpi/rectangle_white_radius_15.xml
  app/src/main/res/drawable-xhdpi/rectangle_white_radius_8.xml
  app/src/main/res/drawable-xhdpi/rectangle_yellow_radius_5.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/logout_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 준경🔥, In Progress

#42 [feat] 가게 제보, 가게 수정 구현, 내가쓴리뷰, 스크랩한 식당 이동 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyScrapActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyActivity.kt
  app/src/main/res/drawable-xxxhdpi/rectangle_red_radius_36.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/activity_my_scrap.xml
  app/src/main/res/layout/activity_profile_modify.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#55 [feat] #54 - setting 화면 디자인
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/SettingActivity.kt
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 준경🔥, In Progress

#50 [feat] 길찾기 다이얼로그 뷰 구현
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/SettingActivity.kt
  app/src/main/java/org/helfoome/presentation/restaurant/MapSelectionBottomDialogFragment.kt
  app/src/main/res/drawable/rectangle_white_top_radius_24.xml
  app/src/main/res/layout/dialog_map_selection.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 영진🐶, DONE

#61 [feat] 회원 탈퇴 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/WithdrawalActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/SettingActivity.kt
  app/src/main/res/drawable/rectangle_border_gray_radius_8.xml
  app/src/main/res/drawable/rectangle_red_radius_36.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/withdraw_dialog.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#62 [ui] 메뉴 토글 버튼이 스크롤 영역에 포함되도록 변경
  app/src/main/res/layout/fragment_menu.xml
Labels: 영진🐶, DONE

#59 [feat] 외식대처법 ui 구현
  app/src/main/java/org/helfoome/presentation/custom/EatingOutTipView.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantEatingOutTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantMenuViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantTabAdapter.kt
  app/src/main/java/org/helfoome/presentation/type/EatingOutTipType.kt
  app/src/main/res/drawable/ic_check_circle_green.xml
  app/src/main/res/drawable/ic_check_circle_red.xml
  app/src/main/res/drawable/ic_how_to_eat.xml
  app/src/main/res/drawable/ic_reason_for_recommendation.xml
  app/src/main/res/layout/fragment_eating_out.xml
  app/src/main/res/layout/item_eating_out_tip.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 영진🐶, DONE

#66 [feat] 리뷰 탭 ui 구현
  app/src/main/java/org/helfoome/domain/entity/BlogReviewInfo.kt
  app/src/main/java/org/helfoome/domain/entity/RecentSearchInfo.kt
  app/src/main/java/org/helfoome/domain/entity/ReviewInfo.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/custom/HashtagView.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantEatingOutTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantMenuTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantBlogReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantGeneralReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantImageAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantMenuAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantTabAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/viewmodel/RestaurantMenuViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/viewmodel/RestaurantReviewViewModel.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/util/ItemDecorationUtil.kt
  app/src/main/java/org/helfoome/util/ext/ContextExt.kt
  app/src/main/res/drawable/rectangle_boarder_radius_12.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_blog_review.xml
  app/src/main/res/layout/item_general_review.xml
  app/src/main/res/layout/item_hashtag.xml
  app/src/main/res/layout/item_review_image.xml
  app/src/main/res/layout/layout_look_map.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 영진🐶, DONE

#65 [FEAT] 최근 검색어 로직 구현
  app/src/main/java/org/helfoome/data/EmptyFile.kt
  app/src/main/java/org/helfoome/data/local/dao/SearchDao.kt
  app/src/main/java/org/helfoome/data/local/entity/SearchData.kt
  app/src/main/java/org/helfoome/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/helfoome/di/RepositoryModule.kt
  app/src/main/java/org/helfoome/domain/EmptyFile.kt
  app/src/main/java/org/helfoome/domain/entity/RecentSearchInfo.kt
  app/src/main/java/org/helfoome/domain/repository/SearchRepository.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchViewModel.kt
  app/src/main/java/org/helfoome/presentation/search/adapter/RecentAdapter.kt
  app/src/main/res/layout/item_recent_word.xml
  app/src/main/res/layout/layout_look_map.xml
Labels: 다빈😺, DONE

#69 [FEAT] 스크랩한 식당 뷰 구현
  app/src/main/java/org/helfoome/domain/entity/ScrapInfo.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyScrapActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyScrapAdapter.kt
  app/src/main/res/drawable-xxxhdpi/rectangle_red_radius_36.xml
  app/src/main/res/drawable/rectangle_border_gray_radius_8.xml
  app/src/main/res/layout/activity_my_scrap.xml
  app/src/main/res/layout/item_scrap.xml
  app/src/main/res/layout/view_helfoome_empty.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 다빈😺, DONE

#57 [feat] 프로필 편집 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/custom/SnackBarView.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyViewModel.kt
  app/src/main/res/anim/anim_snackbar_bottom_top.xml
  app/src/main/res/anim/anim_snackbar_top_down.xml
  app/src/main/res/drawable-hdpi/rectangle_grey_radius_77.xml
  app/src/main/res/drawable-xhdpi/rectangle_border_gray_radius_8.xml
  app/src/main/res/drawable-xhdpi/rectangle_grey_radius_36.xml
  app/src/main/res/drawable-xhdpi/rectangle_red_radius_36.xml
  app/src/main/res/drawable-xhdpi/selector_btn_modify.xml
  app/src/main/res/drawable/rectangle_grey_radius_77.xml
  app/src/main/res/layout/activity_profile_modify.xml
  app/src/main/res/layout/logout_dialog.xml
  app/src/main/res/layout/view_snackbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#72 [feat] #71 - 스플래쉬 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/LoginActivity.kt
  app/src/main/java/org/helfoome/presentation/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/raw/android_loading.json
  app/src/main/res/raw/splash_android.json
Labels: 준경🔥, In Progress

#78 [feat] #76 - 맵 ViewModel 임시 구현
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyActivity.kt
  app/src/main/res/drawable/ic_marker_green_big.xml
  app/src/main/res/drawable/ic_marker_red_big.xml
Labels: 준경🔥, In Progress

#80 [feat] 리뷰 작성 페이지 ui 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/custom/HashtagView.kt
  app/src/main/java/org/helfoome/presentation/custom/StarScore.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantGeneralReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/review/RestaurantReviewWritingViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/org/helfoome/presentation/type/GoodPointHashtagType.kt
  app/src/main/java/org/helfoome/presentation/type/HashtagViewType.kt
  app/src/main/java/org/helfoome/presentation/type/TasteHashtagType.kt
  app/src/main/java/org/helfoome/util/BindingAdapter.kt
  app/src/main/java/org/helfoome/util/KeyboardVisibilityUtils.kt
  app/src/main/res/color/selector_tag_background_color.xml
  app/src/main/res/color/selector_tag_text_color.xml
  app/src/main/res/drawable/ic_custom_rating_bar.xml
  app/src/main/res/drawable/ic_rating_bar_empty.xml
  app/src/main/res/drawable/ic_rating_bar_fill.xml
  app/src/main/res/drawable/rectangle_boarder_gray_radius_14.xml
  app/src/main/res/drawable/rectangle_boarder_red_radius_14.xml
  app/src/main/res/drawable/rectangle_radius_8.xml
  app/src/main/res/drawable/selector_tag_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/layout/item_general_review.xml
  app/src/main/res/layout/item_hashtag.xml
  app/src/main/res/layout/item_hashtag_restaurant_summary.xml
  app/src/main/res/layout/item_hashtag_review_tab.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 영진🐶, DONE

#82 [feat] #81 - 갤러리 및 사진 촬영 관련 ui 구현
  app/src/main/java/org/helfoome/presentation/review/GalleryBottomDialogFragment.kt
  app/src/main/java/org/helfoome/presentation/review/GalleryImageAdapter.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/res/drawable/ic_black_circle_delete.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/rectangle_boarder_dash_gray_radius_8.xml
  app/src/main/res/layout/dialog_gallery_image_selection.xml
  app/src/main/res/layout/item_camera.xml
  app/src/main/res/layout/item_gallery_image.xml
  app/src/main/res/values/strings.xml
Labels: 영진🐶, In Progress

#85 [feat] 나의 리뷰 보기 구현
  app/src/main/java/org/helfoome/domain/entity/MyReviewInfo.kt
  app/src/main/java/org/helfoome/domain/entity/ReviewInfo.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/res/drawable/ic_go.xml
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/item_general_my_review.xml
  app/src/main/res/layout/myreview_dialog.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#87 [FEAT] 검색 뷰 지도 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/di/AppModule.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MyScrapActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/adapter/MyScrapAdapter.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchViewModel.kt
  app/src/main/java/org/helfoome/presentation/search/adapter/RecentAdapter.kt
  app/src/main/java/org/helfoome/presentation/search/adapter/ResultAdapter.kt
  app/src/main/java/org/helfoome/presentation/search/adapter/SearchMapTopAdapter.kt
  app/src/main/java/org/helfoome/util/BindingAdapter.kt
  app/src/main/res/drawable/ic_empty.xml
  app/src/main/res/drawable/selector_delete.xml
  app/src/main/res/layout/activity_map_select.xml
  app/src/main/res/layout/activity_my_scrap.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/dialog_restaurant_list.xml
  app/src/main/res/layout/dialog_search_restaurant_detail.xml
  app/src/main/res/layout/item_recent_word.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/layout/layout_look_map.xml
Labels: 다빈😺, DONE

#89 [feat] DialogUtil 구현 및 DialogUtil 적용
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/WithdrawalActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/util/DialogUtil.kt
Labels: 준경🔥, In Progress

#90 [ui] 식당 상세 뷰 ui 수정
  app/src/main/java/org/helfoome/domain/entity/BlogReviewInfo.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/custom/OpeningTimeView.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/viewmodel/RestaurantReviewViewModel.kt
  app/src/main/res/drawable/ic_helfoome_place_holder.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_blog_review.xml
  app/src/main/res/layout/item_general_review.xml
  app/src/main/res/layout/item_menu.xml
  app/src/main/res/values/themes.xml
Labels: 영진🐶, DONE

#91 [init] #63 - 서버 기초 세팅
  app/build.gradle.kts
  app/src/main/java/org/helfoome/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/helfoome/data/local/HFMSharedPreference.kt
  app/src/main/java/org/helfoome/di/AppModule.kt
  app/src/main/java/org/helfoome/di/NetworkModule.kt
Labels: 다빈😺, 준경🔥, In Progress

#93 [ui] #92 - 지도 및 식당 상세뷰 연결
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
Labels: 영진🐶, DONE

#96 [fix] 메인 뷰 마진 및 패딩 수정
  app/src/main/res/layout/activity_main.xml
Labels: 다빈😺, DONE

#100 [fix] 다이얼로그 크기 수정 및 햄버거 로직 변경
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/WithdrawalActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/SettingActivity.kt
  app/src/main/java/org/helfoome/presentation/type/FoodType.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_drawer_header.xml
  app/src/main/res/layout/activity_profile_modify.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/dialog_myreview.xml
  app/src/main/res/layout/dialog_withdraw.xml
  app/src/main/res/layout/logout_dialog.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#102 [ui] #101 - 식당 상세페이지 탭 레이아웃 버튼 클릭 시 리플 효과 제거
  app/src/main/res/layout/dialog_restaurant_detail.xml
Labels: 영진🐶, DONE

#103 [fix] 레이팅 바 + 스크롤 이슈 해결
  app/src/main/java/org/helfoome/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/res/drawable-hdpi/ic_star_gray.webp
  app/src/main/res/drawable-hdpi/ic_star_green.webp
  app/src/main/res/drawable-mdpi/ic_star_gray.webp
  app/src/main/res/drawable-mdpi/ic_star_green.webp
  app/src/main/res/drawable-xhdpi/ic_star_gray.webp
  app/src/main/res/drawable-xhdpi/ic_star_green.webp
  app/src/main/res/drawable-xxhdpi/ic_star_gray.webp
  app/src/main/res/drawable-xxhdpi/ic_star_green.webp
  app/src/main/res/drawable-xxxhdpi/ic_star_gray.webp
  app/src/main/res/drawable-xxxhdpi/ic_star_green.webp
  app/src/main/res/drawable/ic_rating_bar_empty.xml
  app/src/main/res/drawable/ic_rating_bar_fill.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
Labels: 다빈😺, In Progress

#107 [feat] 리뷰 탭 및 리뷰 작성 뷰 ui 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/RestaurantReviewWritingViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/org/helfoome/util/ItemDecorationUtil.kt
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/layout/fragment_review.xml
Labels: 영진🐶, DONE

#108 [feat] snackbar 애니메이션 수정 및 네이버 지도 초기 디폴트 값 설정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyActivity.kt
  app/src/main/res/anim/anim_snackbar_bottom_top_fast.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile_modify.xml
Labels: 준경🔥, In Progress

#115 [add] #114 - 서버통신을 위한 BaseResponse 파일 추가
  app/src/main/java/org/helfoome/data/model/request/EmptyFile.kt
  app/src/main/java/org/helfoome/data/model/response/BaseResponse.kt
Labels: 영진🐶, DONE

#113 [chore] 상태바 투명하게 바꾸기
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/SplashActivity.kt
  app/src/main/java/org/helfoome/util/ext/StatusBarUtil.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/values/themes.xml
Labels: 다빈😺, DONE

#120 [feat] 식당 요약 뷰 api 연동 구현
  app/src/main/java/org/helfoome/data/model/response/ResponseRestaurantSummary.kt
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/RestaurantService.kt
  app/src/main/java/org/helfoome/di/RepositoryModule.kt
  app/src/main/java/org/helfoome/di/ServiceModule.kt
  app/src/main/java/org/helfoome/domain/entity/RestaurantInfo.kt
  app/src/main/java/org/helfoome/domain/repository/RestaurantRepository.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/custom/OpeningTimeView.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/util/BindingAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
Labels: 영진🐶, DONE

#122 [feat] #110 프로필 조회 구현
  app/src/main/java/org/helfoome/data/local/HFMSharedPreference.kt
  app/src/main/java/org/helfoome/data/model/request/RequestProfile.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseLogin.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseProfile.kt
  app/src/main/java/org/helfoome/data/repository/ProfileRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/AuthService.kt
  app/src/main/java/org/helfoome/data/service/NaverAuthService.kt
  app/src/main/java/org/helfoome/di/RepositoryModule.kt
  app/src/main/java/org/helfoome/domain/repository/ProfileRepository.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/res/layout/activity_main_drawer_header.xml
Labels: 준경🔥, In Progress

#125 [feat] 외식대처법 api 연동
  app/src/main/java/org/helfoome/data/model/response/ResponseEatingOutTip.kt
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/RestaurantService.kt
  app/src/main/java/org/helfoome/domain/entity/EatingOutTipInfo.kt
  app/src/main/java/org/helfoome/domain/repository/RestaurantRepository.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantEatingOutTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantMenuTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/viewmodel/RestaurantMenuViewModel.kt
  app/src/main/res/layout/fragment_eating_out.xml
Labels: 영진🐶, DONE

#123 [feat] 식당 검색 API 연동
  app/src/main/java/org/helfoome/data/datasource/RemoteSearchDataSource.kt
  app/src/main/java/org/helfoome/data/model/request/EmptyFile.kt
  app/src/main/java/org/helfoome/data/model/request/RequestProfile.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseAutoComplete.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseLogin.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseProfile.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseRestaurantSummary.kt
  app/src/main/java/org/helfoome/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/NaverAuthService.kt
  app/src/main/java/org/helfoome/data/service/SearchService.kt
  app/src/main/java/org/helfoome/di/NetworkModule.kt
  app/src/main/java/org/helfoome/di/RepositoryModule.kt
  app/src/main/java/org/helfoome/di/ServiceModule.kt
  app/src/main/java/org/helfoome/domain/entity/AutoCompleteKeywordInfo.kt
  app/src/main/java/org/helfoome/domain/repository/SearchRepository.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchViewModel.kt
  app/src/main/java/org/helfoome/presentation/search/adapter/AutoCompleteAdapter.kt
  app/src/main/java/org/helfoome/util/ext/ResourceExt.kt
  app/src/main/java/org/helfoome/util/ext/ViewExt.kt
  app/src/main/res/layout/item_auto_complete_word.xml
  app/src/main/res/values/strings.xml
Labels: 다빈😺, DONE

#127 [feat] 프로필 수정 api 구현
  app/src/main/java/org/helfoome/data/model/request/RequestProfileModify.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseProfileModify.kt
  app/src/main/java/org/helfoome/data/repository/ProfileModifyRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/AuthService.kt
  app/src/main/java/org/helfoome/data/service/KakaoAuthService.kt
  app/src/main/java/org/helfoome/di/RepositoryModule.kt
  app/src/main/java/org/helfoome/domain/repository/ProfileModifyRepository.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: 준경🔥, In Progress

#132 [feat] 헬푸미 리뷰 조회 api 연동
  app/src/main/java/org/helfoome/data/datasource/RemoteRestaurantDataSource.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseHFMReview.kt
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/repository/ReviewRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/RestaurantService.kt
  app/src/main/java/org/helfoome/data/service/ReviewService.kt
  app/src/main/java/org/helfoome/di/RepositoryModule.kt
  app/src/main/java/org/helfoome/di/ServiceModule.kt
  app/src/main/java/org/helfoome/domain/entity/ReviewInfo.kt
  app/src/main/java/org/helfoome/domain/repository/RestaurantRepository.kt
  app/src/main/java/org/helfoome/domain/repository/ReviewRepository.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantImageAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/viewmodel/RestaurantReviewViewModel.kt
Labels: 영진🐶, DONE

#134 [feat] 메인 지도 뷰 api 연동
  app/src/main/java/org/helfoome/data/model/response/ResponseMap.kt
  app/src/main/java/org/helfoome/data/repository/MapRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/MapService.kt
  app/src/main/java/org/helfoome/di/RepositoryModule.kt
  app/src/main/java/org/helfoome/di/ServiceModule.kt
  app/src/main/java/org/helfoome/domain/entity/MarkerInfo.kt
  app/src/main/java/org/helfoome/domain/repository/MapRepository.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
Labels: 준경🔥, In Progress

#135 [feat] 블로그 리뷰 조회 api 연동
  app/src/main/java/org/helfoome/data/datasource/RemoteRestaurantDataSource.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseBlogReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseHFMReview.kt
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/repository/ReviewRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/RestaurantService.kt
  app/src/main/java/org/helfoome/domain/entity/BlogReviewInfo.kt
  app/src/main/java/org/helfoome/domain/entity/HFMReviewInfo.kt
  app/src/main/java/org/helfoome/domain/repository/RestaurantRepository.kt
  app/src/main/java/org/helfoome/domain/repository/ReviewRepository.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantBlogReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantGeneralReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantImageAdapter.kt
  app/src/main/res/layout/item_blog_review.xml
  app/src/main/res/layout/item_general_review.xml
Labels: 영진🐶, DONE

#136 [feat] 식당 검색 및 카드 리스트 조회 API 연동
  app/src/main/java/org/helfoome/data/datasource/RemoteSearchDataSource.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseProfileModify.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseSearchCard.kt
  app/src/main/java/org/helfoome/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/SearchService.kt
  app/src/main/java/org/helfoome/domain/entity/SearchResultInfo.kt
  app/src/main/java/org/helfoome/domain/repository/SearchRepository.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchViewModel.kt
  app/src/main/java/org/helfoome/presentation/search/adapter/SearchMapTopAdapter.kt
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/layout/dialog_restaurant_list.xml
  app/src/main/res/layout/item_auto_complete_word.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/layout/layout_look_map.xml
  app/src/main/res/layout/layout_recent_word.xml
  app/src/main/res/values/strings.xml
Labels: 다빈😺, DONE

#142 [feat] 리프레시 토큰 로직 짜기
  app/build.gradle.kts
  app/src/main/java/org/helfoome/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/helfoome/data/local/HFMSharedPreference.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseRefresh.kt
  app/src/main/java/org/helfoome/data/service/KakaoAuthService.kt
  app/src/main/java/org/helfoome/data/service/NaverAuthService.kt
  app/src/main/java/org/helfoome/di/NetworkModule.kt
  app/src/main/java/org/helfoome/presentation/SplashActivity.kt
  gradle/libs.versions.toml
Labels: 다빈😺

#144 [feat] 유저리뷰 모아보기 api 연동
  app/src/main/java/org/helfoome/data/model/response/ResponseMyReviewList.kt
  app/src/main/java/org/helfoome/data/repository/ReviewRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/ReviewService.kt
  app/src/main/java/org/helfoome/domain/entity/MyReviewInfo.kt
  app/src/main/java/org/helfoome/domain/entity/MyReviewListInfo.kt
  app/src/main/java/org/helfoome/domain/repository/ReviewRepository.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewViewModel.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/res/layout/item_general_my_review.xml
Labels: 준경🔥, In Progress

#145 [mod] #139 - SerializedName 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseHFMReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseMyReviewList.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  gradle.properties
Labels: 준경🔥, In Progress

#147 [feat] 스크랩한 식당 모아보기 API 연동
  app/src/main/java/org/helfoome/data/datasource/RemoteScrapDataSource.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseHFMReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseMyReviewList.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseScrapData.kt
  app/src/main/java/org/helfoome/data/repository/ScrapRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/ScrapService.kt
  app/src/main/java/org/helfoome/di/RepositoryModule.kt
  app/src/main/java/org/helfoome/di/ServiceModule.kt
  app/src/main/java/org/helfoome/domain/entity/ScrapInfo.kt
  app/src/main/java/org/helfoome/domain/repository/ScrapRepository.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/scrap/MyScrapActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/ScrapViewModel.kt
  app/src/main/java/org/helfoome/presentation/scrap/adapter/MyScrapAdapter.kt
  app/src/main/res/layout/activity_my_scrap.xml
  app/src/main/res/layout/item_scrap.xml
Labels: 다빈😺, DONE

#149 [mod] #146 - elevation, margin, drawaerlayout 수정
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: 준경🔥, In Progress

#151 [feat] 리뷰 작성 페이지 내 갤러리 및 사진촬영 ui 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/helfoome/presentation/review/GalleryBottomDialogFragment.kt
  app/src/main/java/org/helfoome/presentation/review/GalleryImageAdapter.kt
  app/src/main/java/org/helfoome/presentation/review/RestaurantReviewWritingViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/org/helfoome/presentation/type/ReviewImageType.kt
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/dialog_gallery_image_selection.xml
  app/src/main/res/layout/item_camera.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 영진🐶, DONE

#153 [feat] 리뷰 불러오기 api 구현
  app/src/main/java/org/helfoome/data/model/request/RequestEditReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseHFMReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseMyReviewEdit.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseMyReviewList.kt
  app/src/main/java/org/helfoome/data/repository/ReviewRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/KakaoAuthService.kt
  app/src/main/java/org/helfoome/data/service/NaverAuthService.kt
  app/src/main/java/org/helfoome/data/service/ReviewService.kt
  app/src/main/java/org/helfoome/domain/entity/HFMReviewInfo.kt
  app/src/main/java/org/helfoome/domain/entity/MyReviewListInfo.kt
  app/src/main/java/org/helfoome/domain/entity/ReviewImage.kt
  app/src/main/java/org/helfoome/domain/repository/ReviewRepository.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/custom/StarScore.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewViewModel.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyViewModel.kt
  app/src/main/java/org/helfoome/presentation/drawer/SettingActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantImageAdapter.kt
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/dialog_my_review_delete.xml
  app/src/main/res/layout/dialog_my_review_edit.xml
  app/src/main/res/layout/dialog_myreview.xml
  app/src/main/res/layout/item_general_my_review.xml
  app/src/main/res/layout/item_review_image.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#152 [feat] 유저 리뷰 삭제 api 연동
  app/src/main/java/org/helfoome/data/repository/ReviewRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/KakaoAuthService.kt
  app/src/main/java/org/helfoome/data/service/NaverAuthService.kt
  app/src/main/java/org/helfoome/data/service/ReviewService.kt
  app/src/main/java/org/helfoome/domain/repository/ReviewRepository.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewViewModel.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/res/layout/activity_my_review.xml
Labels: 다빈😺, DONE

#160 [mod] 전체적으로 api 연동 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseBlogReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseHFMReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseScrap.kt
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/repository/ScrapRepositoryImpl.kt
  app/src/main/java/org/helfoome/domain/repository/RestaurantRepository.kt
  app/src/main/java/org/helfoome/domain/repository/ScrapRepository.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantEatingOutTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/viewmodel/RestaurantMenuViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/layout/fragment_eating_out.xml
Labels: 영진🐶, In Progress

#161 [feat] 닉네임 볼드 처리
  app/src/main/java/org/helfoome/data/model/response/ResponseProfile.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_drawer_header.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#167 [feat] 서치 뷰 UI 플로우 구현
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/RestaurantService.kt
  app/src/main/java/org/helfoome/data/service/SearchService.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/res/layout/dialog_restaurant_list.xml
  app/src/main/res/layout/layout_look_map.xml
  app/src/main/res/layout/layout_search_empty.xml
Labels: 다빈😺, DONE

#170 [feat] #168 - 해당 리뷰 작성 확인
  app/src/main/java/org/helfoome/data/model/response/ResponseReviewCheck.kt
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/repository/ReviewRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/ReviewService.kt
  app/src/main/java/org/helfoome/domain/repository/ReviewRepository.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/res/color/selector_btn_review.xml
  app/src/main/res/values/themes.xml
Labels: 준경🔥, In Progress

#174 [mod] #173 - 프로필 변경 수정
  app/src/main/java/org/helfoome/data/model/request/RequestEditReview.kt
  app/src/main/java/org/helfoome/data/model/request/RequestProfile.kt
  app/src/main/java/org/helfoome/data/model/request/RequestProfileModify.kt
  app/src/main/java/org/helfoome/data/model/request/RequestReviewEdit.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseProfileModify.kt
  app/src/main/java/org/helfoome/data/service/NaverAuthService.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: 준경🔥, In Progress

#175 [ui] 전체적인 ui 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseBlogReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseEatingOutTip.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseRestaurantDetail.kt
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/repository/ReviewRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/RestaurantService.kt
  app/src/main/java/org/helfoome/data/service/ReviewService.kt
  app/src/main/java/org/helfoome/domain/entity/EatingOutTipInfo.kt
  app/src/main/java/org/helfoome/domain/repository/RestaurantRepository.kt
  app/src/main/java/org/helfoome/domain/repository/ReviewRepository.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/custom/StarScore.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantEatingOutTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/res/drawable/ic_eating_out_empty.xml
  app/src/main/res/drawable/ic_hambuger.xml
  app/src/main/res/drawable/ic_review_empty.xml
  app/src/main/res/drawable/rectangle_border_radius_5.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_drawer_header.xml
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/activity_profile_modify.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/dialog_my_review_delete.xml
  app/src/main/res/layout/dialog_my_review_edit.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/layout/dialog_search_restaurant_detail.xml
  app/src/main/res/layout/dialog_withdraw.xml
  app/src/main/res/layout/fragment_eating_out.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_blog_review.xml
  app/src/main/res/layout/item_general_my_review.xml
  app/src/main/res/layout/item_general_review.xml
  app/src/main/res/layout/item_menu.xml
  app/src/main/res/layout/item_scrap.xml
  app/src/main/res/layout/view_chip_food.xml
  app/src/main/res/layout/view_eating_out_empty.xml
  app/src/main/res/layout/view_helfoome_empty.xml
  app/src/main/res/layout/view_rating_bar.xml
  app/src/main/res/layout/view_review_empty.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 영진🐶, DONE

#177 [feat] 메인 뷰 카테고리 필터링 적용
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
Labels: 다빈😺, DONE

#182 [feat] #181 - 리뷰 작성 스낵바 구현
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
Labels: 준경🔥, In Progress

#184 [mod] 전체적인 ui 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseHFMReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseRestaurantDetail.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantMenuTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/java/org/helfoome/presentation/type/ReviewType.kt
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_menu.xml
Labels: 영진🐶, DONE

#187 [feat] 줌 축척 조절
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/SplashActivity.kt
  app/src/main/java/org/helfoome/util/ext/StatusBarUtil.kt
Labels: 다빈😺, DONE

#190 [feat] 기타 디자인 QA
  app/src/main/java/org/helfoome/data/local/HFMSharedPreference.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseRestaurantDetail.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseScrapData.kt
  app/src/main/java/org/helfoome/domain/entity/ScrapInfo.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/SplashActivity.kt
  app/src/main/java/org/helfoome/presentation/WithdrawalActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MapSelectActivity.kt
  app/src/main/res/layout/activity_map_select.xml
  app/src/main/res/layout/item_scrap.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/layout/layout_look_map.xml
  app/src/main/res/values/themes.xml
Labels: 다빈😺, DONE

#193 [feat] #192 - 백 버튼 크기 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseRestaurantDetail.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/ProfileModifyActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/SettingActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MyScrapActivity.kt
Labels: 준경🔥, In Progress

#197 [add] 마커필터 확장함수 유틸 추가
  app/src/main/java/org/helfoome/util/ext/MarkerFilter.kt
Labels: 다빈😺

#198 [feat] 전체적인 ui 수정
  app/src/main/java/org/helfoome/data/datasource/RemoteRestaurantDataSource.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseBlogReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseReview.kt
  app/src/main/java/org/helfoome/data/repository/RestaurantRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/RestaurantService.kt
  app/src/main/java/org/helfoome/domain/entity/HFMReviewInfo.kt
  app/src/main/java/org/helfoome/domain/entity/ReviewImage.kt
  app/src/main/java/org/helfoome/domain/repository/RestaurantRepository.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/custom/HashtagView.kt
  app/src/main/java/org/helfoome/presentation/custom/OpeningTimeView.kt
  app/src/main/java/org/helfoome/presentation/drawer/MyReviewActivity.kt
  app/src/main/java/org/helfoome/presentation/drawer/adapter/MyReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantReviewTabFragment.kt
  app/src/main/java/org/helfoome/presentation/restaurant/adapter/RestaurantBlogReviewAdapter.kt
  app/src/main/java/org/helfoome/presentation/review/RestaurantReviewWritingViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/org/helfoome/presentation/type/DayOfWeekType.kt
  app/src/main/java/org/helfoome/util/BindingAdapter.kt
  app/src/main/java/org/helfoome/util/DateUtil.kt
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
  app/src/main/res/layout/fragment_eating_out.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_blog_review.xml
  app/src/main/res/layout/item_general_my_review.xml
  app/src/main/res/layout/item_general_review.xml
  app/src/main/res/layout/item_hashtag_restaurant_summary.xml
  app/src/main/res/layout/item_menu.xml
  app/src/main/res/values/strings.xml
Labels: 영진🐶, In Progress

#200 [mod] #199 - 스크랩 아이템 마진 수정
  app/src/main/res/drawable/ic_btn_bookmark_active.xml
  app/src/main/res/drawable/ic_btn_bookmark_inactive.xml
  app/src/main/res/drawable/selector_btn_scrap.xml
  app/src/main/res/layout/item_scrap.xml
Labels: 준경🔥, In Progress

#201 [feat] 서치뷰 로직 구현 완료
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/presentation/search/adapter/ResultAdapter.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/dialog_restaurant_detail.xml
Labels: 다빈😺, DONE

#205 [feat] 리뷰 작성 및 리뷰 탭 ui 수정
  app/src/main/java/org/helfoome/data/service/ReviewService.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/review/RestaurantReviewWritingViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/res/layout/item_hashtag_review_tab.xml
Labels: 영진🐶, DONE

#218 [mod] 디테일 수정
  app/src/main/java/org/helfoome/SplashSecondActivity.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseBlogReview.kt
  app/src/main/java/org/helfoome/data/model/response/ResponseLogin.kt
  app/src/main/java/org/helfoome/data/repository/WithdrawalRepositoryImpl.kt
  app/src/main/java/org/helfoome/data/service/KakaoAuthService.kt
  app/src/main/java/org/helfoome/data/service/NaverAuthService.kt
  app/src/main/java/org/helfoome/domain/entity/HFMReviewInfo.kt
  app/src/main/java/org/helfoome/domain/entity/ReviewImage.kt
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/MainViewModel.kt
  app/src/main/java/org/helfoome/presentation/restaurant/RestaurantEatingOutTabFragment.kt
  app/src/main/java/org/helfoome/presentation/review/RestaurantReviewWritingViewModel.kt
  app/src/main/java/org/helfoome/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/org/helfoome/presentation/scrap/MyScrapActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/presentation/type/DayOfWeekType.kt
  app/src/main/java/org/helfoome/util/BindingAdapter.kt
  app/src/main/java/org/helfoome/util/DateUtil.kt
  app/src/main/res/drawable/ic_marker_mini.xml
  app/src/main/res/layout/item_scrap.xml
  app/src/main/res/layout/layout_look_map.xml
  app/src/main/res/values/strings.xml
Labels: 준경🔥, In Progress

#222 [fix] #221 - 로그인에 실패하는 버그 수정
  app/src/main/java/org/helfoome/data/model/response/ResponseLogin.kt
Labels: 영진🐶, DONE

#223 [feat] 식당 상세 뷰에서 distance값 보여주기 및 단위 포맷 적용
  app/src/main/java/org/helfoome/presentation/MainActivity.kt
  app/src/main/java/org/helfoome/presentation/search/SearchActivity.kt
  app/src/main/java/org/helfoome/util/BindingAdapter.kt
  app/src/main/res/layout/dialog_restaurant_detail.xml
Labels: 영진🐶, DONE
